### PR TITLE
Merge 'algae' branch into 'main' branch

### PR DESCRIPTION
**Pull request by GaYeongKim**
- pm2_batch: calibration of pm2 model with batch experiment data
- pm2_ecorecover: calibration and validation of pm2 model with continuous online monitoring data obtained from EcoRecover plant

### CODE REVIEW

**Comment by GaYeongKim** [comment]
@yalinli2 @joyxyz1994  The errors seem to occur due to 'optuna', a new optimizer package I used..... Should we include 'optuna' package into Exposan?

**Comment by yalinli2** [comment]
Thanks @GaYeongKim ! Let me think of/take a look at this in the next couple of days (or during Thanksgiving if I can't get to it over the weekend...), I've been thinking of cutting down dependencies that are not core to QSDsan so that the environment is easier to build on the cloud, maybe I should get back to have separate config files for installation and testing

**Comment by yalinli2** [comment]
Oh and does this need to use the `algae` branch of QSDsan?

**Comment by GaYeongKim** [comment]
Not necessarily? There are no changes in 'algae' branch. It is rather 87 commits behind 'main' branch. I was afraid that modeling would fail due to the new qsdsan updates, so I left the 'algae' branch. I will merge it too sooner or later after checking everything is okay!

**Comment by yalinli2** [comment]
Ohhh I see, sounds good and thanks!

**Comment by yalinli2** [comment]
@GaYeongKim , thanks so much for the contribution (and having the README)! I made the following changes:

* Updated `algae` with `main` (otherwise tests in other modules won't pass), none of those changes should affect PM2 modules since the modules are compartmentalized.
* Added codes (based on the ones in READMEs) for testing, they will make sure the systems can be loaded and simulated, but won't check for results. You can add the number checks if you want.
* Updated README to include a note on `optuna`, I didn't include it in the dependency at the current stage, maybe one day when we include an optimization module in QSDsan we should/will `optuna` as a dependency.
* Since all the remote tests are run using the `main` branch of QSDsan and they passed, you can get the `algae` branch updated, but I'm not sure if this will affect any of your numbers. However not updating for a really long time could also be a problem... As sometimes there are bug fixes that should be merged in (Jianan had a bad experience...)

Anyway, I'm good with merging in this PR if you think it's OK!

**Comment by GaYeongKim** [comment]
@yalinli2  I have checked a few key simulations with QSDsan main branch, and it seems to be working! I guess this is ready to merge! (I'm not authorized to merge, plz merge this!)

**Pull request merged**
