### PR TITLE
PFAS-HTL module refactor

### PR DESCRIPTION
**Pull request by yalinli2**
Currently I've finished the module-wide refactoring to minimize repetitive codes. The next step is to make sure the refactored module can get the same results as the existing `pfas`, I'll convert this to a formal PR once that's done.

### CODE REVIEW

**Comment by yalinli2** [comment]
@jiananf2 OK I'm done with the first round of refactoring, I actually didn't update the units by much, but:
1. separate model creation from system creation, now there's `create_system` (in systems.py) and `create_model` (in models.py), which can be easily used in another place to create the system and model
2. add a `configuration` kwarg in `create_system` and `create_model` to determine whether to use "baseline", "no_P", or "PSA" configuration, this way we don't need to have three sets of different functions that would be a headache if in the future we want to make updates

I also went ahead and compare the results before and after the refactoring (see attached), I compared all the metrics in `model.metrics_at_baseline()` and they are pretty close for all three configurations, the largest diff comes from HXN's capital cost, which is off by <0.2%, I checked and looks like it was due to one heating utility (seems to belong to the boiler in A390 (D3), the distillation column after HTL to separate heavy oil from diesel). Seems like this utility could be offset in the original module but not in the refactored one. I'm not exactly sure why, it could be a tiny difference somewhere that leads to this divergence... I'm not too concerned over it given it was so small, but let me know if you want to dig deeper into it.

the comparison spreadsheet:
[comparison.xlsx](https://github.com/QSD-Group/EXPOsan/files/10325949/comparison.xlsx)

Feel free to make updates or leave comments, if you feel good about it then you can approve and merge it in, thanks!

**Comment by yalinli2** [comment]
Oh btw, you'll want to update your local `biosteam@qsdsan`, `thermosteam@qsdsan`, and `qsdsan@pfas`, all of them have substantial updates recently

**Comment by yalinli2** [comment]
After we settle on the refactoring, I'd like to clean up some of the unit codes (e.g., we probably can update the `HT` with a kwarg like `include_PSA` with some modification on the methods instead of having separate `HT` and `HT_PSA` classes). Then we'll get those migrated to QSDsan. I'll also add tests on both QSDsan and here in EXPOsan to make sure all these changes won't affect the results.

**Comment by jiananf2** [comment]
Thanks for refactoring the codes! One thing I noticed was the input for H2SO4_Tank (T200) and RSP1 (S300) were empty (therefore, their costs and environmental impacts are also empty). I think it is because the system path has been altered.

**Comment by yalinli2** [comment]
@jiananf2 good catch! I used the auto-system creation function so the path might not be the optimal one, I added one explicit line to let the system simulate in the `create_system` function, can you see if it fixes the problem (including if it gives expected results when loading a different sample)? If the problem persists, we can go back to explicitly set the system path. Thanks!

**Comment by jiananf2** [comment]
The problem was fixed! Attached is a new comparison for three configurations. And the results look good!
[comparison.xlsx](https://github.com/QSD-Group/EXPOsan/files/10329050/comparison.xlsx)

**Comment by yalinli2** [comment]
wonderful!

**Pull request merged**
